#pragma once

//LEFT MOUTH MOTOR
#define MOTOR_1_A_PIN 53
#define MOTOR_1_B_PIN 52
#define MOTOR_1_MAX_MILLIS_OPENED 4500

//LEFT HEAD MOTOR
#define MOTOR_2_A_PIN 50
#define MOTOR_2_B_PIN 51
#define MOTOR_2_MAX_MILLIS_OPENED 4500

//CENTER MOUTH MOTOR
#define MOTOR_3_A_PIN 49
#define MOTOR_3_B_PIN 48
#define MOTOR_3_MAX_MILLIS_OPENED 4500

//CENTER HEAD MOTOR
#define MOTOR_6_A_PIN 46
#define MOTOR_6_B_PIN 47
#define MOTOR_6_MAX_MILLIS_OPENED 10000

//RIGHT MOUTH MOTOR
#define MOTOR_4_A_PIN 45
#define MOTOR_4_B_PIN 44
#define MOTOR_4_MAX_MILLIS_OPENED 4500

//RIGHT HEAD MOTOR
#define MOTOR_5_A_PIN 42
#define MOTOR_5_B_PIN 43
#define MOTOR_5_MAX_MILLIS_OPENED 4500

//DMX VARIABLES
#define RXEN_PIN 2