#pragma once

//DMX VARIABLES
#define DMX_SLAVE_ADDRESS 310
#define DMX_SLAVE_CHANNELS 30

//DMX CHANNELS
#define DMX_SHOW_CHANNEL 1
#define DMX_PRESHOW_CHANNEL 2
#define DMX_EXAMPLESHOW_CHANNEL 3

#define DMX_SETHOMEPOSITIONS_CHANNEL 4

#define DMX_LEFTMOUTH_MANUAL_CHANNEL 5
#define DMX_LEFTMOUTH_MANUALFIXED_CHANNEL 6
#define DMX_LEFTMOUTH_AUTO_CHANNEL 7

#define DMX_CENTRALMOUTH_MANUAL_CHANNEL 8
#define DMX_CENTRALMOUTH_MANUALFIXED_CHANNEL 9
#define DMX_CENTRALMOUTH_AUTO_CHANNEL 10

#define DMX_RIGHTMOUTH_MANUAL_CHANNEL 11
#define DMX_RIGHTMOUTH_MANUALFIXED_CHANNEL 12
#define DMX_RIGHTMOUTH_AUTO_CHANNEL 13

#define DMX_LEFTHEAD_MANUAL_CHANNEL 14
#define DMX_LEFTHEAD_MANUALFIXED_CHANNEL 15
#define DMX_LEFTHEAD_AUTO_CHANNEL 16

#define DMX_RIGHTHEAD_MANUAL_CHANNEL 17
#define DMX_RIGHTHEAD_MANUALFIXED_CHANNEL 18
#define DMX_RIGHTHEAD_AUTO_CHANNEL 19

#define DMX_CENTRALHEAD_MANUALFIXED_CHANNEL 20
#define DMX_CENTRALHEAD_AUTO_CHANNEL 21